#!/bin/sh

git stash -q --keep-index

# run the tests with the gradle wrapper
./gradlew check -Penv=local

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew check' exit code
exit $RESULT
